
@HostAddress = http://localhost:5202

GET {{HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{HostAddress}}/random/
Accept: application/json

###



GET {{HostAddress}}/SampleCache/
Accept: application/json

###
